ALTER TABLE links ADD COLUMN block_ipv6 INTEGER DEFAULT 0;
ALTER TABLE links ADD COLUMN ip_allowlist TEXT DEFAULT '';
ALTER TABLE campaigns ADD COLUMN block_ipv6 INTEGER DEFAULT 0;
ALTER TABLE campaigns ADD COLUMN ip_allowlist TEXT DEFAULT '';
